// generated by http://www.jsonschema2pojo.org
package sgf.gateway.service.geocode.geobytes.jackson;

import com.fasterxml.jackson.annotation.*;

import javax.annotation.Generated;
import java.util.HashMap;
import java.util.Map;

@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
        "geobytes"
})
public class GeobytesResponse {

    @JsonProperty("geobytes")
    private Geobytes geobytes;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    /**
     * @return The geobytes
     */
    @JsonProperty("geobytes")
    public Geobytes getGeobytes() {
        return geobytes;
    }

    /**
     * @param geobytes The geobytes
     */
    @JsonProperty("geobytes")
    public void setGeobytes(Geobytes geobytes) {
        this.geobytes = geobytes;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
