// generated by http://www.jsonschema2pojo.org
package sgf.gateway.service.geocode.geobytes.jackson;

import com.fasterxml.jackson.annotation.*;

import javax.annotation.Generated;
import java.util.HashMap;
import java.util.Map;

@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
        "countryid",
        "country",
        "fips",
        "iso2",
        "iso3",
        "ison",
        "internet",
        "comment",
        "regionid",
        "region",
        "code",
        "adm",
        "cityid",
        "city",
        "latitude",
        "longitude",
        "timezone",
        "dmaid",
        "dma",
        "market",
        "certainty",
        "locationcode",
        "ipaddress"
})
public class Geobytes {

    @JsonProperty("countryid")
    private Integer countryid;
    @JsonProperty("country")
    private String country;
    @JsonProperty("fips")
    private String fips;
    @JsonProperty("iso2")
    private String iso2;
    @JsonProperty("iso3")
    private String iso3;
    @JsonProperty("ison")
    private Integer ison;
    @JsonProperty("internet")
    private String internet;
    @JsonProperty("comment")
    private String comment;
    @JsonProperty("regionid")
    private Integer regionid;
    @JsonProperty("region")
    private String region;
    @JsonProperty("code")
    private String code;
    @JsonProperty("adm")
    private String adm;
    @JsonProperty("cityid")
    private Integer cityid;
    @JsonProperty("city")
    private String city;
    @JsonProperty("latitude")
    private Double latitude;
    @JsonProperty("longitude")
    private Double longitude;
    @JsonProperty("timezone")
    private String timezone;
    @JsonProperty("dmaid")
    private String dmaid;
    @JsonProperty("dma")
    private String dma;
    @JsonProperty("market")
    private String market;
    @JsonProperty("certainty")
    private Integer certainty;
    @JsonProperty("locationcode")
    private String locationcode;
    @JsonProperty("ipaddress")
    private String ipaddress;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    /**
     * @return The countryid
     */
    @JsonProperty("countryid")
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * @param countryid The countryid
     */
    @JsonProperty("countryid")
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * @return The country
     */
    @JsonProperty("country")
    public String getCountry() {
        return country;
    }

    /**
     * @param country The country
     */
    @JsonProperty("country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * @return The fips
     */
    @JsonProperty("fips")
    public String getFips() {
        return fips;
    }

    /**
     * @param fips The fips
     */
    @JsonProperty("fips")
    public void setFips(String fips) {
        this.fips = fips;
    }

    /**
     * @return The iso2
     */
    @JsonProperty("iso2")
    public String getIso2() {
        return iso2;
    }

    /**
     * @param iso2 The iso2
     */
    @JsonProperty("iso2")
    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }

    /**
     * @return The iso3
     */
    @JsonProperty("iso3")
    public String getIso3() {
        return iso3;
    }

    /**
     * @param iso3 The iso3
     */
    @JsonProperty("iso3")
    public void setIso3(String iso3) {
        this.iso3 = iso3;
    }

    /**
     * @return The ison
     */
    @JsonProperty("ison")
    public Integer getIson() {
        return ison;
    }

    /**
     * @param ison The ison
     */
    @JsonProperty("ison")
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * @return The internet
     */
    @JsonProperty("internet")
    public String getInternet() {
        return internet;
    }

    /**
     * @param internet The internet
     */
    @JsonProperty("internet")
    public void setInternet(String internet) {
        this.internet = internet;
    }

    /**
     * @return The comment
     */
    @JsonProperty("comment")
    public String getComment() {
        return comment;
    }

    /**
     * @param comment The comment
     */
    @JsonProperty("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * @return The regionid
     */
    @JsonProperty("regionid")
    public Integer getRegionid() {
        return regionid;
    }

    /**
     * @param regionid The regionid
     */
    @JsonProperty("regionid")
    public void setRegionid(Integer regionid) {
        this.regionid = regionid;
    }

    /**
     * @return The region
     */
    @JsonProperty("region")
    public String getRegion() {
        return region;
    }

    /**
     * @param region The region
     */
    @JsonProperty("region")
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * @return The code
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * @param code The code
     */
    @JsonProperty("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return The adm
     */
    @JsonProperty("adm")
    public String getAdm() {
        return adm;
    }

    /**
     * @param adm The adm
     */
    @JsonProperty("adm")
    public void setAdm(String adm) {
        this.adm = adm;
    }

    /**
     * @return The cityid
     */
    @JsonProperty("cityid")
    public Integer getCityid() {
        return cityid;
    }

    /**
     * @param cityid The cityid
     */
    @JsonProperty("cityid")
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * @return The city
     */
    @JsonProperty("city")
    public String getCity() {
        return city;
    }

    /**
     * @param city The city
     */
    @JsonProperty("city")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * @return The latitude
     */
    @JsonProperty("latitude")
    public Double getLatitude() {
        return latitude;
    }

    /**
     * @param latitude The latitude
     */
    @JsonProperty("latitude")
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * @return The longitude
     */
    @JsonProperty("longitude")
    public Double getLongitude() {
        return longitude;
    }

    /**
     * @param longitude The longitude
     */
    @JsonProperty("longitude")
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * @return The timezone
     */
    @JsonProperty("timezone")
    public String getTimezone() {
        return timezone;
    }

    /**
     * @param timezone The timezone
     */
    @JsonProperty("timezone")
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    /**
     * @return The dmaid
     */
    @JsonProperty("dmaid")
    public String getDmaid() {
        return dmaid;
    }

    /**
     * @param dmaid The dmaid
     */
    @JsonProperty("dmaid")
    public void setDmaid(String dmaid) {
        this.dmaid = dmaid;
    }

    /**
     * @return The dma
     */
    @JsonProperty("dma")
    public String getDma() {
        return dma;
    }

    /**
     * @param dma The dma
     */
    @JsonProperty("dma")
    public void setDma(String dma) {
        this.dma = dma;
    }

    /**
     * @return The market
     */
    @JsonProperty("market")
    public String getMarket() {
        return market;
    }

    /**
     * @param market The market
     */
    @JsonProperty("market")
    public void setMarket(String market) {
        this.market = market;
    }

    /**
     * @return The certainty
     */
    @JsonProperty("certainty")
    public Integer getCertainty() {
        return certainty;
    }

    /**
     * @param certainty The certainty
     */
    @JsonProperty("certainty")
    public void setCertainty(Integer certainty) {
        this.certainty = certainty;
    }

    /**
     * @return The locationcode
     */
    @JsonProperty("locationcode")
    public String getLocationcode() {
        return locationcode;
    }

    /**
     * @param locationcode The locationcode
     */
    @JsonProperty("locationcode")
    public void setLocationcode(String locationcode) {
        this.locationcode = locationcode;
    }

    /**
     * @return The ipaddress
     */
    @JsonProperty("ipaddress")
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * @param ipaddress The ipaddress
     */
    @JsonProperty("ipaddress")
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
