package sgf.gateway.service.security.impl.acegi;

import org.springframework.dao.DataAccessException;
import org.springframework.security.authentication.encoding.PasswordEncoder;
import sgf.gateway.utils.security.FreeBSDCrypt;

/**
 * Implementation of Spring PasswordEncoder that encodes and validates password using the MD5-crypt algorithm.
 */
public class FreeBSDCryptPasswordEncoder implements PasswordEncoder {

    private static final int START_SALT = 3;

    private static final int STOP_SALT = 11;

    /**
     * Note that this method does not use any external salt, since the salt is generated by the underlying MD5Crypt class on a per-password basis.
     *
     * @param rawPass the un-encoded (clear text) password.
     * @param salt    the external salt, which is ignored by this implementation.
     * @return the encoded password.
     * @throws DataAccessException thrown in case of encoding errors.
     */
    public String encodePassword(String rawPass, Object salt) throws DataAccessException {

        return FreeBSDCrypt.crypt(rawPass);
    }

    /**
     * Note that this method parses the encryptd password to retrieve the salt that is used to encrypt the clear text password, before performing a comparison.
     *
     * @param encPass the encrypted password.
     * @param rawPass the un-encrypted (clear text) password.
     * @param salt    the external salt (ignored by this implementation).
     * @return true if is password valid.
     * @throws DataAccessException
     */
    public boolean isPasswordValid(String encPass, String rawPass, Object salt) throws DataAccessException {

        // retrieve salt from encrypted password
        // example format: $1$LvwVZUS8$FvU.yQWntcwpRiD6CLrQR1
        String encryptedSalt = encPass.substring(START_SALT, STOP_SALT);

        // use salt to encrypt the decrypted password
        String newEncryptedPassword = FreeBSDCrypt.crypt(rawPass, encryptedSalt);

        boolean equals = newEncryptedPassword.equals(encPass);

        return equals;
    }
}
